### ISSUE TITLE
Clarify that this plugin is meant to be used with FigmaJam, not Figma Design

### ISSUE THREAD

**Issue by LordSimal** [planetscale/figma-diagram-generator#1]
I was banging my head to the wall because I was wondering why I always get 
```
promise rejection: TypeError: not a function
```
when creating tables with foreign key connections.

I pinpointed it to the call `connectElements()` because as I have found out `figma.createConnector();` is only available in FigmaJam.

After I created a FigmaJam project instead of a "normal" Figma Project everything works fine.

**Comment by bddicken** [comment]
Updated the README to clarify! Thanks for the feedback.

**Comment by bddicken** [comment]
Updated the README to clarify! Thanks for the feedback.
